# To install hooks, run:
# pre-commit install --hook-type pre-commit
# pre-commit install --hook-type commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        args: ['--ignore-words-list', 'ontop']

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v11.0.1
    hooks:
    - id: clang-format
      types_or: [c]

  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: v1.6.26.11
    hooks:
    - id: actionlint
      types_or: [yaml]

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.13.0
    hooks:
    - id: markdownlint
      types_or: [markdown]

  - repo: local
    hooks:

      # Python scripts
      - id: pylint
        name: Check python Client
        # Only display messages, no score, disable few errors
        entry: pylint -j 0 --rc tests/setup.cfg
        language: system
        types: [python]
        files: '^tests\/.*$'

      - id: pylint
        name: Check python Tool
        # Only display messages, no score, disable few errors
        entry: pylint -j 0 --rc pytools/setup.cfg
        language: system
        types: [python]
        files: '^pytools\/.*$'
