# To install hooks, run:
# pre-commit install --hook-type pre-commit
# pre-commit install --hook-type commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-added-large-files
        exclude: 'pnpm-lock\.yaml$'
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        args: ['--ignore-words-list', 'ontop']
        exclude: 'pnpm-lock\.yaml$'

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.8
    hooks:
      - id: clang-format
        types_or: [c]

  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: v1.7.12.24
    hooks:
      - id: actionlint
        types_or: [yaml]
        args: [-shellcheck='' -pyflakes='']

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.22.1
    hooks:
      - id: markdownlint-cli2
        types_or: [markdown]
        exclude: CHANGELOG.md

  - repo: https://github.com/PyCQA/pylint
    rev: v4.0.5
    hooks:
      - id: pylint
        name: Check python Client
        types: [python]
        args: ['--jobs=0', '--rcfile=tests/ragger/setup.cfg']
        files: '^tests\/.*$'
        additional_dependencies: ['pytest', 'ragger[speculos,ledgerwallet]', 'ledgered']

      - id: pylint
        name: Check python Tool
        types: [python]
        args: ['--jobs=0', '--rcfile=pytools/setup.cfg']
        files: '^pytools\/.*$'
