name: Build and run functional tests using ragger through reusable workflow

# This workflow will build the app.
# It calls a reusable workflow developed by Ledger's internal developer team to build the application and upload the
# resulting binaries.
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  build_application:
    name: Build application using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      upload_app_binaries_artifact: "compiled_app_binaries"
      run_for_devices: '["nanos", "nanox", "nanosp"]'
