name: Checks on the Python client

# This workflow performs some checks on the Python client used by the Application tests
# It is there to help us maintain a level of quality in our codebase and does not have to be kept on forked
# applications.

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  lint_ragger_tests:
    name: Lint Ragger tests
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_python_checks.yml@v1
    with:
      run_type_check: true
      src_directory: .
      setup_directory: tests/ragger
      req_directory: tests/ragger

  lint_pytools:
    name: Lint pytools
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_python_checks.yml@v1
    with:
      run_type_check: true
      src_directory: .
      setup_directory: pytools
      req_directory: pytools
      additional_packages: libpcsclite-dev
