name: Unit testing with Codecov coverage checking

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  job_unit_test:
    name: Call Ledger unit_test
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_unit_tests.yml@v1
    secrets: inherit
    with:
      test_directory: tests/unit
